### ISSUE TITLE
BUG: MinkGoutteDriver requirement assumption

### ISSUE THREAD

**Issue by phptek** [silverstripe-labs/silverstripe-behat-extension#94]
In framework's `behat.yml` there's a reference to `goutte: ~` but the behat module has no such reference to `MinkGoutteDriver` in its composer file that's required. This means running the following from the CLI results in an error:

    #> vendor/bin/behat @mysite --definitions=i

    [RuntimeException]
    Install MinkGoutteDriver in order to activate goutte session.

Modifying composer.json thus, fixes the problem:

    "require": {
        `"behat/mink-goutte-driver": "*"
    }

Framework + CMS 3.1.13

**Comment by chillu** [comment]
This has been removed from the `cms` module and `installer` in 2014 (https://github.com/silverstripe/silverstripe-cms/commit/e1f82aba4998a1627c9395e0a2d3277089d60fcd and https://github.com/silverstripe/silverstripe-installer/commit/10dc891fee9fb1bd1bca6c7ffaea742fb6eb365a). I can't find it in the `framework` module in any maintained release branch.

Found a mention of it in some SS Behat docs, removed from there: https://github.com/silverstripe-labs/silverstripe-behat-extension/commit/70a6d7777feb6ca25a7d11cb20eaa28f29e9ee0d.

Does that fix it for you? I'd rather not require `behat/mink-goutte-driver` just to satisfy this (unused) configuration, since to my knowledge the SS Behat contexts haven't really been tested with goutte. A lot of the contexts rely on JS execution, so won't work in a pure PHP headless browser like goutte.
